version: "3"
services:
  ui_backend:
    image: "nguoithichkhampha/metaflow-service-ui_backend"
    restart: unless-stopped
    container_name: "metaflow-service-ui_backend"
    ports:
      - "${MF_UI_METADATA_PORT:-8083}:${MF_UI_METADATA_PORT:-8083}"
    environment:
      - MF_METADATA_DB_HOST=db
      - MF_METADATA_DB_PORT=${MF_METADATA_DB_PORT:-5433}
      - MF_METADATA_DB_USER=${MF_METADATA_DB_USER:-postgres}
      - MF_METADATA_DB_PSWD=${MF_METADATA_DB_PSWD:-postgres}
      - MF_METADATA_DB_NAME=postgres
      - MF_UI_METADATA_PORT=${MF_UI_METADATA_PORT:-8083}
      - MF_UI_METADATA_HOST=${MF_UI_METADATA_HOST:-0.0.0.0}
      - MF_METADATA_DB_POOL_MIN=1
      - MF_METADATA_DB_POOL_MAX=10
      - METAFLOW_S3_RETRY_COUNT=0
      - LOGLEVEL=INFO
      - AIOPG_ECHO=0
      - UI_ENABLED=0
      - PREFETCH_RUNS_SINCE=2592000 # 30 days in seconds
      - PREFETCH_RUNS_LIMIT=1 # Prefetch only one run
      - S3_NUM_WORKERS=2
      - CACHE_ARTIFACT_MAX_ACTIONS=4
      - CACHE_DAG_MAX_ACTIONS=4
      - CACHE_LOG_MAX_ACTIONS=4
      - CACHE_ARTIFACT_STORAGE_LIMIT=16000000
      - CACHE_DAG_STORAGE_LIMIT=16000000
      - WS_POSTPROCESS_CONCURRENCY_LIMIT=8
      - FEATURE_PREFETCH_DISABLE=0
      - FEATURE_CACHE_DISABLE=0
      - FEATURE_S3_DISABLE=0
      - FEATURE_REFINE_DISABLE=0
      - FEATURE_WS_DISABLE=0
      - FEATURE_HEARTBEAT_DISABLE=0
      - FEATURE_DB_LISTEN_DISABLE=0
      - FEATURE_ARTIFACT_SEARCH=1
      - FEATURE_FOREACH_VAR_SEARCH=1
      - FEATURE_ARTIFACT_TABLE=1
      - CUSTOM_QUICKLINKS=$CUSTOM_QUICKLINKS
      - NOTIFICATIONS=$NOTIFICATIONS
      - GA_TRACKING_ID=none
      - PLUGINS=$PLUGINS
      - METAFLOW_DEFAULT_DATASTORE=${METAFLOW_DEFAULT_DATASTORE:-s3}
      - METAFLOW_DATASTORE_SYSROOT_S3=${METAFLOW_DATASTORE_SYSROOT_S3:-s3://metaflow}
      - METAFLOW_S3_ENDPOINT_URL=${METAFLOW_S3_ENDPOINT_URL:-http://minio:9000/}
      - AWS_ACCESS_KEY_ID=${MINIO_ACCESS_KEY:-minioadmin}
      - AWS_SECRET_ACCESS_KEY=${MINIO_SECRET_KEY:-minioadmin}
    depends_on:
      - metadata
      - minio
  metadata:
    image: "netflixoss/metaflow_metadata_service"
    restart: unless-stopped
    container_name: "metadata_service"
    ports:
      - "${MF_MIGRATION_PORT:-8082}:${MF_MIGRATION_PORT:-8082}"
      - "${MF_METADATA_PORT:-8090}:${MF_METADATA_PORT:-8090}"
    volumes:
      - .:/code
    environment:
      - MF_METADATA_DB_HOST=db
      - MF_METADATA_DB_PORT=${MF_METADATA_DB_PORT:-5433}
      - MF_METADATA_DB_USER=${MF_METADATA_DB_USER:-postgres}
      - MF_METADATA_DB_PSWD=${MF_METADATA_DB_PSWD:-postgres}
      - MF_METADATA_DB_NAME=postgres
      - MF_MIGRATION_ENDPOINTS_ENABLED=1
      - MF_METADATA_PORT=${MF_METADATA_PORT:-8090}
      - MF_METADATA_HOST=${MF_METADATA_HOST:-0.0.0.0}
      - MF_MIGRATION_PORT=${MF_MIGRATION_PORT:-8082}
    links:
      - db
  db:
    image: "postgres:11"
    restart: unless-stopped
    container_name: "my_postgres"
    environment:
      POSTGRES_USER: ${MF_METADATA_DB_USER:-postgres}
      POSTGRES_PASSWORD: ${MF_METADATA_DB_PSWD:-postgres}
      POSTGRES_DB: postgres
      PGPORT: ${MF_METADATA_DB_PORT:-5433}
    ports:
      - "${MF_METADATA_DB_PORT:-5433}:${MF_METADATA_DB_PORT:-5433}"
    volumes:
      - my_dbdata:/var/lib/postgresql/data2
  minio:
    container_name: "minio"
    image: minio/minio:RELEASE.2024-12-18T13-15-44Z
    restart: unless-stopped
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY:-minioadmin}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY:-minioadmin}
    volumes:
      - minio_vol:/minio_data
    command: minio server /minio_data --console-address :${MINIOPORT_SERVER:-9001}
    ports:
      - ${MINIOPORT_SERVER:-9001}:${MINIOPORT_SERVER:-9001}
      - ${MINIOPORT_ENDPOINT:-9000}:9000    
volumes:
  my_dbdata:
  minio_vol:
