version: "3"
services:
  metaflow-ui:
    image: "nguoithichkhampha/metaflow-ui:latest"
    restart: unless-stopped
    container_name: "metaflow-ui"
    ports:
      - 3000:3000
    environment:
      - METAFLOW_SERVICE=http://localhost:8083/  
